### PR TITLE
Migrate from javax to jakarta

### PR DESCRIPTION
**Pull request by jtreminio-dropbox**
Clone PR of #316 

Original description:

This PR contains the following changes:
* upgrade of OpenAPI generator to 7.0.1
* upgrade from jersey2 to jersey3
* regenerated .java classes (using ./run-build)

After packaging and deploying the result artifact to the official Maven repo it should be possible to use Dropbox Sign Java SDK with Spring Boot.

### CODE REVIEW

**Comment by jtreminio-dropbox** [comment]
We can't merge this as-is, research shows that moving from javax to jakarta will break backwards compatibility with existing users.

We are deciding on the course of action here:

1. A new, non-BC major version of the Java SDK (ie v2.0.0), or
2. Maintaining a new jakarta-specific version of the Java SDK

**Comment by christiangoudreau** [comment]
Well, Java 8 and 11 doesn't receive any new security updates since 2019... moving to jarkata seems like the way to move forward. To me 1. should be the way to go. 

Can you let me know the steps you want me to do to test this as I have never tried to run this repository before ?

**Comment by jspaetzel** [comment]
I've made a few changes on this branch to move this along some
* fixed conflicts
* update version to 2.0-dev
* created a [v1 branch](https://github.com/hellosign/hellosign-openapi/tree/java-v1) in case we decide to do any patches in the future for any of the 1.x versions. But the goal should be to use v2 from main going forward.

**Comment by jspaetzel** [comment]
I've been continuing this some, ive created another branch https://github.com/hellosign/hellosign-openapi/pull/352
this'll divide the java sdk into v1 & v2 where this jakarta variant will live in v2. This will allow us to continue releasing javax variants as new features arrive without any major difficulty.

**Pull request closed without merging**
